version: "3"

services:
  webserver:
    links: 
      - database
  database:
    build:
      context: "./bin/${DATABASE}"
    container_name: "${NAME_PREFIX}_database"
    restart: 'always'
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      # - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql:delegated
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      - ${MYSQL_BACKUP_DIR-./data/mysqlbackup}:/var/backups
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      # SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));